name: CI/CD Nunjucks

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3
        
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12' 
      
      - name: Instalar dependencias
        run: npm install
      
      - name: Lanzar tests
        run: npm test  

      - name: Lanzar linter
        run: npm run lint 

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist